// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Connector
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// W3C Payment Method Data for Microsoft Pay
    /// </summary>
    public partial class MicrosoftPayMethodData
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftPayMethodData class.
        /// </summary>
        public MicrosoftPayMethodData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftPayMethodData class.
        /// </summary>
        /// <param name="mechantId">Microsoft Pay Merchant ID</param>
        /// <param name="supportedNetworks">Supported payment networks (e.g.,
        /// "visa" and "mastercard")</param>
        /// <param name="supportedTypes">Supported payment types (e.g.,
        /// "credit")</param>
        public MicrosoftPayMethodData(string mechantId = default(string), IList<string> supportedNetworks = default(IList<string>), IList<string> supportedTypes = default(IList<string>))
        {
            MechantId = mechantId;
            SupportedNetworks = supportedNetworks;
            SupportedTypes = supportedTypes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets microsoft Pay Merchant ID
        /// </summary>
        [JsonProperty(PropertyName = "mechantId")]
        public string MechantId { get; set; }

        /// <summary>
        /// Gets or sets supported payment networks (e.g., "visa" and
        /// "mastercard")
        /// </summary>
        [JsonProperty(PropertyName = "supportedNetworks")]
        public IList<string> SupportedNetworks { get; set; }

        /// <summary>
        /// Gets or sets supported payment types (e.g., "credit")
        /// </summary>
        [JsonProperty(PropertyName = "supportedTypes")]
        public IList<string> SupportedTypes { get; set; }

    }
}
