// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Connector
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Result from a completed payment request
    /// </summary>
    public partial class PaymentRequestCompleteResult
    {
        /// <summary>
        /// Initializes a new instance of the PaymentRequestCompleteResult
        /// class.
        /// </summary>
        public PaymentRequestCompleteResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentRequestCompleteResult
        /// class.
        /// </summary>
        /// <param name="result">Result of the payment request
        /// completion</param>
        public PaymentRequestCompleteResult(string result = default(string))
        {
            Result = result;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets result of the payment request completion
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public string Result { get; set; }

    }
}
