// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Bot.Connector
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A receipt card
    /// </summary>
    public partial class ReceiptCard
    {
        /// <summary>
        /// Initializes a new instance of the ReceiptCard class.
        /// </summary>
        public ReceiptCard() { }

        /// <summary>
        /// Initializes a new instance of the ReceiptCard class.
        /// </summary>
        public ReceiptCard(string title = default(string), IList<ReceiptItem> items = default(IList<ReceiptItem>), IList<Fact> facts = default(IList<Fact>), CardAction tap = default(CardAction), string total = default(string), string tax = default(string), string vat = default(string), IList<CardAction> buttons = default(IList<CardAction>))
        {
            Title = title;
            Items = items;
            Facts = facts;
            Tap = tap;
            Total = total;
            Tax = tax;
            Vat = vat;
            Buttons = buttons;
        }

        /// <summary>
        /// Title of the card
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Array of Receipt Items
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<ReceiptItem> Items { get; set; } = new List<ReceiptItem>();

        /// <summary>
        /// Array of Fact Objects   Array of key-value pairs.
        /// </summary>
        [JsonProperty(PropertyName = "facts")]
        public IList<Fact> Facts { get; set; } = new List<Fact>();

        /// <summary>
        /// This action will be activated when user taps on the card
        /// </summary>
        [JsonProperty(PropertyName = "tap")]
        public CardAction Tap { get; set; }

        /// <summary>
        /// Total amount of money paid (or should be paid)
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public string Total { get; set; }

        /// <summary>
        /// Total amount of TAX paid(or should be paid)
        /// </summary>
        [JsonProperty(PropertyName = "tax")]
        public string Tax { get; set; }

        /// <summary>
        /// Total amount of VAT paid(or should be paid)
        /// </summary>
        [JsonProperty(PropertyName = "vat")]
        public string Vat { get; set; }

        /// <summary>
        /// Set of actions applicable to the current card
        /// </summary>
        [JsonProperty(PropertyName = "buttons")]
        public IList<CardAction> Buttons { get; set; } = new List<CardAction>();

    }
}
