C:\source\GitHub\botbuilder-dotnet\libraries\Adapters\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Adapters\Microsoft.Bot.Builder.Adapters.Twilio\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Adapters\Microsoft.Bot.Builder.Adapters.Webex\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\integration\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\integration\Microsoft.Bot.Builder.Integration.ApplicationInsights.Core\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\integration\Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.Core\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\integration\Microsoft.Bot.Builder.Integration.AspNet.WebApi\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.AI.LUIS\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.AI.LuisV3\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.AI.QnA\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.ApplicationInsights\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs.Debugging\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs.Declarative\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs.Flow\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs.Form\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.LanguageGeneration\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Skills\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.StreamingExtensions\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Teams\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.TemplateManager\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Testing\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Configuration\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Connector\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Connector.Teams\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Expressions\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Schema\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Schema.Teams\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.StreamingExtensions\bot_icon.png
C:\source\GitHub\botbuilder-dotnet\libraries\Swagger\bot_icon.png
