// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Schema
{

    /// <summary>
    /// Defines values for ActivityImportance.
    /// </summary>
    public static class ActivityImportance
    {
        /// <summary>
        /// The value for low importance activities.
        /// </summary>
        public const string Low = "low";

        /// <summary>
        /// The value for normal importance activities.
        /// </summary>
        public const string Normal = "normal";

        /// <summary>
        /// The value for high importance activities.
        /// </summary>
        public const string High = "high";
    }
}
