// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Schema
{

    /// <summary>
    /// Defines values for AttachmentLayoutTypes.
    /// </summary>
    public static class AttachmentLayoutTypes
    {
        /// <summary>
        /// The type value for list attachment layouts.
        /// </summary>
        public const string List = "list";

        /// <summary>
        /// The type value for carousel attachment layouts.
        /// </summary>
        public const string Carousel = "carousel";
    }
}
