// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Schema
{

    /// <summary>
    /// Defines values for MessageReactionTypes.
    /// </summary>
    public static class MessageReactionTypes
    {
        /// <summary>
        /// The type for like message reactions.
        /// </summary>
        public const string Like = "like";

        /// <summary>
        /// The type for plus one message reactions.
        /// </summary>
        public const string PlusOne = "plusOne";
    }
}
