// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Schema
{

    /// <summary>
    /// Defines values for TextFormatTypes.
    /// </summary>
    public static class TextFormatTypes
    {
        /// <summary>
        /// The type value for markdown text formats.
        /// </summary>
        public const string Markdown = "markdown";

        /// <summary>
        /// The type value for plain text formats.
        /// </summary>
        public const string Plain = "plain";

        /// <summary>
        /// The type value for xml text formats.
        /// </summary>
        public const string Xml = "xml";
    }
}
