// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Bot.Schema
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Response schema sent back from Bot Framework Token Service required to initiate a user single sign on.
    /// </summary>
    public partial class TokenExchangeResource
    {
        /// <summary>
        /// Initializes a new instance of the TokenExchangeResource class.
        /// </summary>
        public TokenExchangeResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TokenExchangeResource class.
        /// </summary>
        public TokenExchangeResource(string id = default(string), string uri = default(string), string providerId = default(string))
        {
            Id = id;
            Uri = uri;
            ProviderId = providerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// A unique identifier for this token exchange instance
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// The application ID / resource identifier with which to exchange a token on behalf of
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// The identifier of the provider with which to attempt a token exchange
        /// A value of null or empty will default to Azure Active Directory
        /// </summary>
        [JsonProperty(PropertyName = "providerId")]
        public string ProviderId { get; set; }

    }
}
