// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Bot.Builder.Adapters;
using Microsoft.Bot.Builder.Dialogs.Adaptive;
using Microsoft.Bot.Builder.Dialogs.Adaptive.Actions;
using Microsoft.Bot.Builder.Dialogs.Adaptive.Conditions;
using Microsoft.Bot.Builder.Dialogs.Adaptive.Input;
using Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers;
using Microsoft.Bot.Builder.Dialogs.Adaptive.Templates;
using Microsoft.Bot.Builder.Dialogs.Choices;
using Microsoft.Bot.Schema;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;

namespace Microsoft.Bot.Builder.Dialogs.Declarative.Tests
{
    /// <summary>
    /// Test speech priming functionality.
    /// </summary>
    public class PrimingTests
    {
        private static AI.Luis.LuisAdaptiveRecognizer _luis = new AI.Luis.LuisAdaptiveRecognizer()
        {
            // The source would be generated by tooling and this is to distinguish the intent/entity across applications.
            // With package namespacing a component should name it with the package prefix, i.e. Microsoft.Welcome#foo.lu.
            Id = "leaf.lu",
            Recognizes = new[] { "intent1", "entity1", "dlist" },
            DynamicLists = new[]
            {
                    new AI.Luis.DynamicList()
                    {
                        Entity = "dlist",
                        List = new List<AI.LuisV3.ListElement>
                        {
                            new AI.LuisV3.ListElement("value1", new List<string> { "synonym1", "synonym2" })
                        }
                    }
            }
        };

        private static AI.Luis.LuisAdaptiveRecognizer _luisParent = new AI.Luis.LuisAdaptiveRecognizer()
        {
            // The source would be generated by tooling and this is to distinguish the intent/entity across applications.
            // With package namespacing a component should name it with the package prefix, i.e. Microsoft.Welcome#foo.lu.
            Id = "parent.lu",
            Recognizes = new[] { "intentParent", "entityParent", "dlistParent" },
            DynamicLists = new[]
            {
                    new AI.Luis.DynamicList()
                    {
                        Entity = "dlistParent",
                        List = new List<AI.LuisV3.ListElement>
                        {
                            new AI.LuisV3.ListElement("valueParent", new List<string> { "synonym1", "synonym2" })
                        }
                    }
            }
        };

        private static AI.Luis.LuisAdaptiveRecognizer _luisEN = new AI.Luis.LuisAdaptiveRecognizer()
        {
            // The source would be generated by tooling and this is to distinguish the intent/entity across applications.
            // With package namespacing a component should name it with the package prefix, i.e. Microsoft.Welcome#foo.lu.
            Id = "leaf.en-us.lu",
            Recognizes = new[] { "intent1", "entity1", "dlist" },
            DynamicLists = new[]
            {
                    new AI.Luis.DynamicList()
                    {
                        Entity = "dlist",
                        List = new List<AI.LuisV3.ListElement>
                        {
                            new AI.LuisV3.ListElement("value1", new List<string> { "synonym1", "synonym2" })
                        }
                    }
            }
        };

        private static AI.QnA.Recognizers.QnAMakerRecognizer _qna = new AI.QnA.Recognizers.QnAMakerRecognizer();

        private static MultiLanguageRecognizer _multi = new MultiLanguageRecognizer() { Recognizers = new Dictionary<string, Recognizer> { { "en-us", _luisEN }, { string.Empty, _luis } } };

        private static PhraseListHint _dlist = new PhraseListHint("dlist", new[] { "value1", "synonym1", "synonym2" });

        private static PhraseListHint _dlistParent = new PhraseListHint("dlistParent", new[] { "valueParent", "synonym1", "synonym2" });

        private static ActivityTemplate _prompt = new ActivityTemplate("Prompt");

        private static JObject _schema = JObject.Parse(@"
            {
                'type': 'object',
                'properties': {
                    'property1': {
                        'type': 'string',
                        '$entities': ['entity1']
                    }
                }
            }");

        private static AdaptiveDialog _leaf = new AdaptiveDialog()
        {
            Id = "leaf",
            Recognizer = _luis,
            Triggers = new List<OnCondition>
                        {
                            new OnBeginDialog(new List<Dialog>
                            {
                                new Ask()
                                {
                                    Activity = _prompt,
                                    ExpectedProperties = new[] { "property1" }
                                }
                            })
                        },
            Schema = _schema
        };

        private static AdaptiveDialog _parent = new AdaptiveDialog()
        {
            Recognizer = _luisParent,
            Triggers = new List<OnCondition>
            {
                new OnBeginDialog(new List<Dialog>
                {
                    new BeginDialog("leaf")
                })
            }
        };

        private static AdaptiveDialog _withInterruptions = new AdaptiveDialog()
        {
            Recognizer = _luisParent,
            Triggers = new List<OnCondition>
            {
                new OnBeginDialog(new List<Dialog> { new NumberInput { Prompt = _prompt, AllowInterruptions = true } })
            }
        };

        private static AdaptiveDialog _withoutInterruptions = new AdaptiveDialog()
        {
            Recognizer = _luisParent,
            Triggers = new List<OnCondition>
            {
                new OnBeginDialog(new List<Dialog> { new NumberInput { Prompt = _prompt, AllowInterruptions = false } })
            }
        };

        public static IEnumerable<object[]> Hints
            => new[]
            {
                new object[] { new PreBuiltHint("prebuilt") },
                new object[] { new LUReferenceHint("intent", "foo.lu") },
                new object[] { new RegexHint("regex", "a*") },
                new object[] { new PhraseListHint("phraseList", new[] { "a b", "c d" }) },
            };

        public static IEnumerable<object[]> ExpectedRecognizer
            => new[]
            {
                // Entity recognizers
                new object[] { new AgeEntityRecognizer(), new[] { new PreBuiltHint("age") } },
                new object[] { new ChannelMentionEntityRecognizer(), new[] { new PreBuiltHint("channelMention") } },
                new object[] { new ConfirmationEntityRecognizer(), new[] { new PreBuiltHint("boolean") } },
                new object[] { new CurrencyEntityRecognizer(), new[] { new PreBuiltHint("currency") } },
                new object[] { new DateTimeEntityRecognizer(), new[] { new PreBuiltHint("datetime") } },
                new object[] { new DimensionEntityRecognizer(), new[] { new PreBuiltHint("dimension") } },
                new object[] { new EmailEntityRecognizer(), new[] { new PreBuiltHint("email") } },
                new object[] { new GuidEntityRecognizer(), new[] { new PreBuiltHint("guid") } },
                new object[] { new HashtagEntityRecognizer(), new[] { new PreBuiltHint("hashtag") } },
                new object[] { new IpEntityRecognizer(), new[] { new PreBuiltHint("ip") } },
                new object[] { new MentionEntityRecognizer(), new[] { new PreBuiltHint("mention") } },
                new object[] { new NumberEntityRecognizer(), new[] { new PreBuiltHint("number") } },
                new object[] { new NumberRangeEntityRecognizer(), new[] { new PreBuiltHint("numberrange") } },
                new object[] { new OrdinalEntityRecognizer(), new[] { new PreBuiltHint("ordinal") } },
                new object[] { new PercentageEntityRecognizer(), new[] { new PreBuiltHint("percentage") } },
                new object[] { new PhoneNumberEntityRecognizer(), new[] { new PreBuiltHint("phonenumber") } },
                new object[] { new RegexEntityRecognizer() { Name = "pattern", Pattern = "a*" }, new[] { new RegexHint("pattern", "a*") } },
                new object[] { new TemperatureEntityRecognizer(), new[] { new PreBuiltHint("temperature") } },
                new object[] { new UrlEntityRecognizer(), new[] { new PreBuiltHint("url") } },

                // Regex Recognizer
                new object[]
                {
                    new RegexRecognizer
                    {
                        Intents = new List<IntentPattern> { new IntentPattern("regexIntent", "intent*") },
                        Entities = new List<EntityRecognizer> { new NumberEntityRecognizer(), new RegexEntityRecognizer { Name = "regexEntity", Pattern = "entity*" } }
                    },
                    new RecognitionHint[] { new RegexHint("regexIntent", "intent*"), new RegexHint("regexEntity", "entity*"), new PreBuiltHint("number") }
                }

                /*
                // LUIS
                new object[]
                {
                    _luis,
                    new[] { new IntentDescription("intent1", "foo.lu") },
                    new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu") },
                    new[] { _dlist }
                },

                // QnA doesn't have any priming information
                new object[]
                {
                    _qna,
                    null, null, null
                },

                // Recognizer set
                new object[]
                {
                    new RecognizerSet() { Recognizers = new List<Recognizer> { new NumberEntityRecognizer(), _luis } },
                    new[] { new IntentDescription("intent1", "foo.lu") },
                    new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu"), new PreBuiltHint("number") },
                    new[] { _dlist }
                },

                // Cross-trained recognizer
                new object[]
                {
                    new CrossTrainedRecognizerSet() { Recognizers = new List<Recognizer> { _luis, new NumberEntityRecognizer() } },
                    new[] { new IntentDescription("intent1", "foo.lu") },
                    new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu"), new PreBuiltHint("number") },
                    new[] { _dlist }
                },

                // Multi language recognizer
                new object[]
                {
                    _multi,
                    new[] { new IntentDescription("intent1", "foo.lu") },
                    new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu") },
                    new[] { _dlist }
                },
                new object[]
                {
                    _multi,
                    new[] { new IntentDescription("intent1", "foo.en-us.lu") },
                    new[] { new PreBuiltHint("entity1", "foo.en-us.lu"), new PreBuiltHint("dlist", "foo.en-us.lu") },
                    new[] { _dlist },
                    "en-us"
                },
                */
            };

        /*
        public static IEnumerable<object[]> ExpectedDialog
            => new[]
            {
                new object[] { new AttachmentInput() { Prompt = _prompt }, null, null, null },  
                new object[] { new ConfirmInput() { Prompt = _prompt }, null, new[] { new PreBuiltHint("boolean") }, null },
                new object[] { new DateTimeInput() { Prompt = _prompt }, null, new[] { new PreBuiltHint("datetimeV2") }, null },
                new object[] { new NumberInput() { Prompt = _prompt }, null, new[] { new PreBuiltHint("number") }, null },
                new object[] { new TextInput() { Prompt = _prompt }, null, null, null },    
                new object[]
                {
                    new ChoiceInput()
                    {
                        Id = "choiceTest",
                        Prompt = _prompt,
                        Choices = new ChoiceSet(new[]
                        {
                            new Choice("value1")
                            {
                                Action = new CardAction(title: "Action"),
                                Synonyms = new List<string> { "synonym1", "synonym2" }
                            }
                        })
                    },
                    null,
                    new[] { new PreBuiltHint("number"), new PreBuiltHint("ordinal") },
                    new[] { new DynamicList("choiceTest", new List<ListElement> { new ListElement("value1", new List<string> { "value1", "Action", "synonym1", "synonym2" }) }) }
                },
                new object[]
                {
                    new ChoiceInput()
                    {
                        Id = "choiceTest",
                        Prompt = _prompt,
                        Choices = new ChoiceSet(new[]
                        {
                            new Choice("value1")
                            {
                                Action = new CardAction(title: "Action"),
                                Synonyms = new List<string> { "synonym1", "synonym2" }
                            }
                        }),
                        RecognizerOptions = new FindChoicesOptions() { NoAction = true, NoValue = true, RecognizeNumbers = false, RecognizeOrdinals = false }
                    },
                    null,
                    null,
                    new[] { new DynamicList("choiceTest", new List<ListElement> { new ListElement("value1", new List<string> { "synonym1", "synonym2" }) }) }
                },
                new object[]
                {
                    _leaf,
                    new[] { new IntentDescription("intent1", "foo.lu") },
                    new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu") },
                    new[] { _dlist },
                    null,
                    new InputContext(
                        "en-us",
                        new RecognizerDescription(null, new[] { new PreBuiltHint("entity1", "foo.lu") }, null),
                        new RecognizerDescription(
                            new[] { new IntentDescription("intent1", "foo.lu") },
                            new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu") },
                            new[] { _dlist }))
                },
                new object[]
                {
                    _parent,
                    new[] { new IntentDescription("intentParent", "parent.lu") },
                    new[] { new PreBuiltHint("entityParent", "parent.lu"), new PreBuiltHint("dlistParent", "parent.lu") },
                    new[] { _dlistParent },
                    null,
                    new InputContext(
                        "en-us",
                        new RecognizerDescription(null, new[] { new PreBuiltHint("entity1", "foo.lu") }, null),
                        new RecognizerDescription(
                            new[] { new IntentDescription("intent1", "foo.lu"), new IntentDescription("intentParent", "parent.lu") },
                            new[] { new PreBuiltHint("entity1", "foo.lu"), new PreBuiltHint("dlist", "foo.lu"), new PreBuiltHint("entityParent", "parent.lu"), new PreBuiltHint("dlistParent", "parent.lu") },
                            new[] { _dlist, _dlistParent }))
                },
                new object[]
                {
                    _withInterruptions,
                    new[] { new IntentDescription("intentParent", "parent.lu") },
                    new[] { new PreBuiltHint("entityParent", "parent.lu"), new PreBuiltHint("dlistParent", "parent.lu") },
                    new[] { _dlistParent },
                    null,
                    new InputContext(
                        "en-us",
                        new RecognizerDescription(null, new[] { new PreBuiltHint("number") }, null),
                        new RecognizerDescription(
                            new[] { new IntentDescription("intentParent", "parent.lu") },
                            new[] { new PreBuiltHint("number"), new PreBuiltHint("entityParent", "parent.lu"), new PreBuiltHint("dlistParent", "parent.lu") },
                            new[] { _dlistParent }))
                },
                new object[]
                {
                    _withoutInterruptions,
                    new[] { new IntentDescription("intentParent", "parent.lu") },
                    new[] { new PreBuiltHint("entityParent", "parent.lu"), new PreBuiltHint("dlistParent", "parent.lu") },
                    new[] { _dlistParent },
                    null,
                    new InputContext(
                        "en-us",
                        new RecognizerDescription(null, new[] { new PreBuiltHint("number") }, null),
                        new RecognizerDescription(
                            null,
                            new[] { new PreBuiltHint("number") },
                            null))
                }
            };*/

        [Theory]
        [MemberData(nameof(Hints))]
        public void HintSeralization(RecognitionHint hint)
        {
            var copiedHint = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(hint)) as JObject;
            var props = hint.GetType().GetProperties();
            foreach (var prop in props)
            {
                var original = prop.GetValue(hint);
                var name = (prop.GetCustomAttributes(typeof(JsonPropertyAttribute), true)[0] as JsonPropertyAttribute).PropertyName;
                var copy = (copiedHint[name] as JValue).Value;
                Assert.Equal(original, copy);
            }
        }

        [Theory]
        [MemberData(nameof(ExpectedRecognizer))]
        public void RecognizerDescriptionTests(Recognizer recognizer, RecognitionHint[] hints, string locale = null)
        {
            CheckDescription(recognizer.GetRecognitionHints(GetTurnContext(locale: locale)), hints);
        }

        /*
        [Theory]
        [MemberData(nameof(ExpectedDialog))]
        public async Task DialogRecognizerDescriptionTests(Dialog dialog, IntentDescription[] intents, PreBuiltHint[] entities, DynamicList[] lists, string locale = null, InputContext input = null)
        {
            var dc = GetTurnContext(dialog);
            await dc.BeginDialogAsync(dialog.Id);
            var activity = PendingActivity(dc);
            var context = activity.InputContext;
            CheckDescription(dialog.GetRecognitionHints(dc, locale), intents, entities, lists);
            if (input != null)
            {
                CheckDescription(context.Possible, input.Possible.Intents.ToArray(), input.Possible.Entities.ToArray(), input.Possible.DynamicLists.ToArray());
                CheckDescription(context.Expected, input.Expected.Intents.ToArray(), input.Expected.Entities.ToArray(), input.Expected.DynamicLists.ToArray());
            }
        }
    */

        private void CheckDescription(IEnumerable<RecognitionHint> description, RecognitionHint[] hints)
        {
            var actual = description.ToArray<RecognitionHint>();
            Assert.Equal(hints.Length, actual.Length);
            foreach (var hint in actual)
            {
                var match = hints.FirstOrDefault(h => h.Name == hint.Name);
                Assert.NotNull(match);
                var hintString = JsonConvert.SerializeObject(hint);
                var matchString = JsonConvert.SerializeObject(match);
                Assert.Equal(matchString, hintString);
            }
        }

        private Activity PendingActivity(DialogContext dc)
            => (dc.Services.Get<ITurnContext>().Adapter as TestAdapter).ActiveQueue.Peek();

        private DialogContext GetTurnContext(Dialog dialog = null, string locale = null)
        {
            var dialogs = new DialogSet();

            // Explicitly add leaf since it is nested in parent
            dialogs.Add(_leaf);
            if (dialog != null)
            {
                dialogs.Add(dialog);
            }

            var turn = new TurnContext(
                    new TestAdapter(TestAdapter.CreateConversation("Priming")),
                    new Activity() { Locale = locale ?? "en-us" });
            var dc = new DialogContext(
                dialogs,
                turn,
                new DialogState());
            dc.Services.Add<ITurnContext>(turn);
            return dc;
        }
    }
}
