// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Bot.Connector.Payments
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    /// <summary>
    /// A request to make a payment
    /// </summary>
    public partial class PaymentRequest
    {
        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest() { }

        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest(string id = default(string), IList<PaymentMethodData> methodData = default(IList<PaymentMethodData>), PaymentDetails details = default(PaymentDetails), PaymentOptions options = default(PaymentOptions), string expires = default(string))
        {
            Id = id;
            MethodData = methodData;
            Details = details;
            Options = options;
            Expires = expires;
        }

        /// <summary>
        /// ID of this payment request
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Allowed payment methods for this request
        /// </summary>
        [JsonProperty(PropertyName = "methodData")]
        public IList<PaymentMethodData> MethodData { get; set; }

        /// <summary>
        /// Details for this request
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public PaymentDetails Details { get; set; }

        /// <summary>
        /// Provides information about the options desired for the payment
        /// request
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        public PaymentOptions Options { get; set; }

        /// <summary>
        /// Expiration for this request, in ISO 8601 duration format (e.g.,
        /// 'P1D')
        /// </summary>
        [JsonProperty(PropertyName = "expires")]
        public string Expires { get; set; }

    }
}
