// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Bot.Connector.Payments
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    /// <summary>
    /// Indicates what the payment request is for and the value asked for
    /// </summary>
    public partial class PaymentItem
    {
        /// <summary>
        /// Initializes a new instance of the PaymentItem class.
        /// </summary>
        public PaymentItem() { }

        /// <summary>
        /// Initializes a new instance of the PaymentItem class.
        /// </summary>
        public PaymentItem(string label = default(string), PaymentCurrencyAmount amount = default(PaymentCurrencyAmount), bool? pending = default(bool?))
        {
            Label = label;
            Amount = amount;
            Pending = pending;
        }

        /// <summary>
        /// Human-readable description of the item
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// Monetary amount for the item
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public PaymentCurrencyAmount Amount { get; set; }

        /// <summary>
        /// When set to true this flag means that the amount field is not
        /// final.
        /// </summary>
        [JsonProperty(PropertyName = "pending")]
        public bool? Pending { get; set; }

    }
}
