// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.Bot.Builder
{
    /// <summary>
    /// A tuple class containing an HTTP status code and a JSON-serializable
    /// object. The HTTP status code is, in the invoke activity scenario, what will
    /// be set in the resulting POST. The body of the resulting POST will be
    /// the JSON-serialized content from the <see cref="Body"/> property.
    /// </summary>
    /// <typeparam name="T">The type of body in the InvokeResponse.</typeparam>
    public class InvokeResponse<T> : InvokeResponse
    {
        /// <summary>Gets or sets the body content for the response.</summary>
        /// <value>The body content.</value>
        /// <remarks>
        /// The POST that is generated in response to the incoming invoke activity
        /// will have a body generated by JSON serializing the object in this field.
        /// </remarks>
        public new T Body
        {
            get => (T)base.Body;
            set => base.Body = value;
        }
    }
}
