en-us
{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":0,"NumberOfPizzas":1,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
[{"endIndex":null,"entity":"2","resolution":null,"role":null,"score":null,"startIndex":null,"type":"DeliveryAddress"},{"endIndex":null,"entity":"byo","resolution":null,"role":null,"score":null,"startIndex":null,"type":"Kind"},{"endIndex":null,"entity":"Hawaiian","resolution":null,"role":null,"score":null,"startIndex":null,"type":"Signature"},{"endIndex":null,"entity":"onions","resolution":null,"role":null,"score":null,"startIndex":null,"type":"BYO.Toppings"},{"endIndex":null,"entity":"peppers","resolution":null,"role":null,"score":null,"startIndex":null,"type":"BYO.Toppings"},{"endIndex":null,"entity":"ice","resolution":null,"role":null,"score":null,"startIndex":null,"type":"BYO.Toppings"},{"endIndex":null,"entity":"5","resolution":null,"role":null,"score":null,"startIndex":null,"type":"NumberOfPizzas"},{"endIndex":null,"entity":"OK","resolution":null,"role":null,"score":null,"startIndex":null,"type":"NotFound"}]
FromUser:"hi"
3
ToUserText:"Welcome to the pizza bot!!!"
ToUserText:"Lets make pizza!!!"
ToUserText:"By \"onions\" toppings did you mean (1. Onions, or 2. Mixed Onions)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":0,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
FromUser:"1"
3
ToUserText:"For toppings I understood Green Peppers, and Onions. \"ice\" is not an option."
ToUserText:"Your address is fine."
ToUserText:"By \"2\" delivery address did you mean (1. 2 Iowa St, or 2. 2 Kansas St)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":0,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
FromUser:"2"
2
ToUserText:"Your address is fine."
ToUserText:"Please select a size (current choice: No Preference) \r\n  1. Medium\r\n  2. Large\r\n  3. Family\r\n  4. No Preference"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":0,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
FromUser:"med"
1
ToUserText:"Please select one or more specials (1. Free drink, or 2. Free garlic bread)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":0,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":null,"Stuffed":0}
FromUser:"drink bread"
1
ToUserText:"Please select a crust \r\n  1. Original\r\n  2. Thin\r\n  3. Stuffed\r\n  4. Fresh Pan\r\n  5. Gluten Free"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":0,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"thin"
1
ToUserText:"Please select a sauce (1. Traditional, 2. Creamy Garlic, or 3. Olive Oil)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"1"
4
ToUserText:"Almost there!!! \r\n* Number Of Pizzas: 5\r\n* Size: Medium\r\n* Kind of pizza: Build your own\r\n* Specials: Free Drink, and Free Garlic Bread\r\n* Half And Half: No\r\n* Crust: Thin\r\n* Sauce: Traditional\r\n* Toppings: Green Peppers, and Onions\r\n* Delivery Address: 2 Kansas St\r\n"
ToUserText:"What we have is a Thin crust Traditional sauce Green Peppers, and Onions pizza"
ToUserText:"Your pizza will cost $50.00"
ToUserText:"Your pizza will cost $10.00 is that OK?"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"y"
1
ToUserText:"Please select one or more coupons (1. Large 20 Percent, 2. Pepperoni 20 Percent, or 3. No Preference) (current choice: No Preference)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"1 2"
1
ToUserText:"Please select a coupon (1. Large 20 Percent, 2. Pepperoni 20 Percent, or 3. No Preference) (current choice: No Preference)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"none"
1
ToUserText:"Please enter a number between 1.0 and 5.0 for rating (current choice: No Preference)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"2.5"
1
ToUserText:"Please enter a date and time for available "
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"2/25/1962 3pm"
1
ToUserText:"Please enter a number between 1 and 3 for bottles (current choice: No Preference)"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"no"
1
ToUserText:"Please enter phone "
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"123-4567"
2
ToUserText:"Rating = 2.5 and [2.50]"
ToUserText:"Would you like a Medium, Thin, Traditional, Green Peppers, and Onions pizza delivered to 2 Kansas St?"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"y"
0
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[7,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Kansas St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":5,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
Result: {"NumberOfPizzas":5,"Size":0,"Kind":4,"Signature":0,"GourmetDelite":0,"Stuffed":0,"BYO":{"Crust":2,"Sauce":1,"HalfAndHalf":false,"Toppings":[7,15],"HalfToppings":null},"Coupons":[1,2],"Coupon":0,"DeliveryAddress":"2 Kansas St","Rating":2.5,"Available":"1962-02-25T15:00:00","Bottles":null,"Specials":["special1","special2"],"Phone":"123-4567"}
