en-us
{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":0,"NumberOfPizzas":1,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
[]
FromUser:"hi"
3
ToUserText:"Welcome to the pizza bot!!!"
ToUserText:"Lets make pizza!!!"
ToUserText:"Please enter a number between 1 and 10 for number of pizzas (current choice: 1)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":0,"NumberOfPizzas":1,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not a number of pizzas option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":0,"NumberOfPizzas":1,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
FromUser:"2"
1
ToUserText:"Please select a size (current choice: No Preference) \r\n  1. Medium\r\n  2. Large\r\n  3. Family\r\n  4. No Preference"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":0,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":null,"Specials":null,"Stuffed":0}
FromUser:"med"
1
ToUserText:"What kind of pizza do you want? \r\n  1. Signature Pizza\r\n  2. Gourmet Delite Pizza\r\n  3. Stuffed Pizza\r\n  4. Build your own"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":0,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":null,"Stuffed":0}
FromUser:"4"
1
ToUserText:"Please select one or more specials (1. Free drink, or 2. Free garlic bread)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":null,"Stuffed":0}
FromUser:"help"
2
ToUserText:"* You are filling in the specials field. Possible responses:\r\n* You can enter one or more numbers 1-2 or words from the descriptions. (Free drink, or Free garlic bread)\r\n* Back: Go back to the previous question.\r\n* Help: Show the kinds of responses you can enter.\r\n* Quit: Quit the form without completing it.\r\n* Reset: Start over filling in the form. (With defaults from your previous entries.)\r\n* Status: Show your progress in filling in the form so far.\r\n* You can switch to another field by entering its name. (Number Of Pizzas, Size, Kind of pizza, Specials, Half And Half, Crust, Sauce, Toppings, Delivery Address, Coupons, Coupon, Rating, Available, Bottles, or Phone). "
ToUserText:"Please select one or more specials (1. Free drink, or 2. Free garlic bread)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":null,"Stuffed":0}
FromUser:"drink bread"
1
ToUserText:"Would you like a half and half? (1. Yes, or 2. No)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"back"
1
ToUserText:"Please select one or more specials (1. Free drink, or 2. Free garlic bread) (current choice: Free Drink, and Free Garlic Bread)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"c"
1
ToUserText:"Would you like a half and half? (1. Yes, or 2. No)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not a half and half option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":null,"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"no"
1
ToUserText:"Please select a crust \r\n  1. Original\r\n  2. Thin\r\n  3. Stuffed\r\n  4. Fresh Pan\r\n  5. Gluten Free"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":0,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"thin"
1
ToUserText:"Please select a sauce (1. Traditional, 2. Creamy Garlic, or 3. Olive Oil)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":0,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"1"
1
ToUserText:"Please select one or more toppings \r\n  1. All except\r\n  2. Beef\r\n  3. Black Olives\r\n  4. Canadian Bacon\r\n  5. Crispy Bacon\r\n  6. Garlic\r\n  7. Green Peppers\r\n  8. Grilled Chicken\r\n  9. Herb And Cheese Blend\r\n  10. Italian Sausage\r\n  11. Artichoke Hearts\r\n  12. Mixed Onions\r\n  13. Mozzarella Cheese\r\n  14. Mushroom\r\n  15. Onions\r\n  16. Parmesan Cheese\r\n  17. Pepperoni\r\n  18. Pineapple\r\n  19. Roma Tomatoes\r\n  20. Salami\r\n  21. Spinach\r\n  22. Sun Dried Tomatoes\r\n  23. Zucchini\r\n  24. Extra Cheese"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"?"
2
ToUserText:"* You are filling in the toppings field. Possible responses:\r\n* You can enter one or more numbers 1-24 or words from the descriptions. (All except, Beef, Black Olives, Canadian Bacon, Crispy Bacon, Garlic, Green Peppers, Grilled Chicken, Herb And Cheese Blend, Italian Sausage, Artichoke Hearts, Mixed Onions, Mozzarella Cheese, Mushroom, Onions, Parmesan Cheese, Pepperoni, Pineapple, Roma Tomatoes, Salami, Spinach, Sun Dried Tomatoes, Zucchini, or Extra Cheese)\r\n* Back: Go back to the previous question.\r\n* Help: Show the kinds of responses you can enter.\r\n* Quit: Quit the form without completing it.\r\n* Reset: Start over filling in the form. (With defaults from your previous entries.)\r\n* Status: Show your progress in filling in the form so far.\r\n* You can switch to another field by entering its name. (Number Of Pizzas, Size, Kind of pizza, Specials, Half And Half, Crust, Sauce, Toppings, Delivery Address, Coupons, Coupon, Rating, Available, Bottles, or Phone). "
ToUserText:"Please select one or more toppings \r\n  1. All except\r\n  2. Beef\r\n  3. Black Olives\r\n  4. Canadian Bacon\r\n  5. Crispy Bacon\r\n  6. Garlic\r\n  7. Green Peppers\r\n  8. Grilled Chicken\r\n  9. Herb And Cheese Blend\r\n  10. Italian Sausage\r\n  11. Artichoke Hearts\r\n  12. Mixed Onions\r\n  13. Mozzarella Cheese\r\n  14. Mushroom\r\n  15. Onions\r\n  16. Parmesan Cheese\r\n  17. Pepperoni\r\n  18. Pineapple\r\n  19. Roma Tomatoes\r\n  20. Salami\r\n  21. Spinach\r\n  22. Sun Dried Tomatoes\r\n  23. Zucchini\r\n  24. Extra Cheese"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not a toppings option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"beef, onion, ice cream"
1
ToUserText:"By \"onion\" toppings did you mean (1. Onions, or 2. Mixed Onions)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not a toppings option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":null},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"onions"
4
ToUserText:"For toppings I understood Beef, and Onions. \"ice cream\" is not an option."
ToUserText:"Almost there!!! \r\n* Number Of Pizzas: 2\r\n* Size: Medium\r\n* Kind of pizza: Build your own\r\n* Specials: Free Drink, and Free Garlic Bread\r\n* Half And Half: No\r\n* Crust: Thin\r\n* Sauce: Traditional\r\n* Toppings: Beef, and Onions\r\n"
ToUserText:"What we have is a Thin crust Traditional sauce Beef, and Onions pizza"
ToUserText:"Please enter delivery address "
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"status"
2
ToUserText:"* Number Of Pizzas: 2\r\n* Size: Medium\r\n* Kind of pizza: Build your own\r\n* Specials: Free Drink, and Free Garlic Bread\r\n* Half And Half: No\r\n* Crust: Thin\r\n* Sauce: Traditional\r\n* Toppings: Beef, and Onions\r\n* Delivery Address: Unspecified\r\n* Coupons: No Preference\r\n* Coupon: No Preference\r\n* Rating: No Preference\r\n* Available: Unspecified\r\n* Bottles: No Preference\r\n* Phone: Unspecified\r\n"
ToUserText:"Please enter delivery address "
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"abc"
2
ToUserText:"Address must start with a number."
ToUserText:"Please enter delivery address "
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"2"
3
ToUserText:"Your address is fine."
ToUserText:"Please enter delivery address "
ToUserText:"By \"2\" delivery address did you mean (1. 2 Iowa St, or 2. 2 Kansas St)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not a delivery address option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":null,"GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"iowa"
3
ToUserText:"Your address is fine."
ToUserText:"Your pizza will cost $20.00"
ToUserText:"Your pizza will cost $10.00 is that OK?"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"y"
1
ToUserText:"Please select one or more coupons (1. Large 20 Percent, 2. Pepperoni 20 Percent, or 3. No Preference) (current choice: No Preference)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":null,"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"1 2"
1
ToUserText:"Please select a coupon (1. Large 20 Percent, 2. Pepperoni 20 Percent, or 3. No Preference) (current choice: No Preference)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"none"
1
ToUserText:"Please enter a number between 1.0 and 5.0 for rating (current choice: No Preference)"
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not a rating option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":null,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"2.5"
1
ToUserText:"Please enter a date and time for available "
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"garbage"
1
ToUserText:"\"garbage\" is not an available option."
State:{"Available":"0001-01-01T00:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"2/25/1962 3pm"
1
ToUserText:"Please enter a number between 1 and 3 for bottles (current choice: No Preference)"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"no"
1
ToUserText:"Please enter phone "
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"1234"
2
ToUserText:"\"1234\" is not a phone option."
ToUserText:"Please enter phone "
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":null,"Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"123-4567"
2
ToUserText:"Rating = 2.5 and [2.50]"
ToUserText:"Would you like a Medium, Thin, Traditional, Beef, and Onions pizza delivered to 2 Iowa St?"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"no"
1
ToUserText:"What do you want to change? (current choice: No Preference) \r\n  1. Number Of Pizzas(2)\r\n  2. Size(Medium)\r\n  3. Kind of pizza(Build your own)\r\n  4. Specials(Free Drink, and Free Garlic Bread)\r\n  5. Half And Half(No)\r\n  6. Crust(Thin)\r\n  7. Sauce(Traditional)\r\n  8. Toppings(Beef, and Onions)\r\n  9. Delivery Address(2 Iowa St)\r\n  10. Coupons(Large 20 Percent, and Pepperoni 20 Percent)\r\n  11. Coupon(No Preference)\r\n  12. Rating(2.5)\r\n  13. Available(2/25/1962 3:00:00 PM)\r\n  14. Bottles(No Preference)\r\n  15. Phone(123-4567)\r\n  16. No Preference"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"toppings"
1
ToUserText:"Please select one or more toppings (current choice: Beef, and Onions) \r\n  1. All except\r\n  2. Beef\r\n  3. Black Olives\r\n  4. Canadian Bacon\r\n  5. Crispy Bacon\r\n  6. Garlic\r\n  7. Green Peppers\r\n  8. Grilled Chicken\r\n  9. Herb And Cheese Blend\r\n  10. Italian Sausage\r\n  11. Artichoke Hearts\r\n  12. Mixed Onions\r\n  13. Mozzarella Cheese\r\n  14. Mushroom\r\n  15. Onions\r\n  16. Parmesan Cheese\r\n  17. Pepperoni\r\n  18. Pineapple\r\n  19. Roma Tomatoes\r\n  20. Salami\r\n  21. Spinach\r\n  22. Sun Dried Tomatoes\r\n  23. Zucchini\r\n  24. Extra Cheese"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,15]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"everything but spinach"
1
ToUserText:"Would you like a Medium, Thin, Traditional, Beef, Black Olives, Canadian Bacon, Crispy Bacon, Garlic, Green Peppers, Grilled Chicken, Herb And Cheese Blend, Italian Sausage, Artichoke Hearts, Mixed Onions, Mozzarella Cheese, Mushroom, Onions, Parmesan Cheese, Pepperoni, Pineapple, Roma Tomatoes, Salami, Sun Dried Tomatoes, Zucchini, and Extra Cheese pizza delivered to 2 Iowa St?"
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
FromUser:"y"
0
State:{"Available":"1962-02-25T15:00:00","Bottles":null,"BYO":{"Crust":2,"HalfAndHalf":false,"HalfToppings":null,"Sauce":1,"Toppings":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24]},"Coupon":0,"Coupons":[1,2],"DeliveryAddress":"2 Iowa St","GourmetDelite":0,"Kind":4,"NumberOfPizzas":2,"Phone":"123-4567","Rating":2.5,"Signature":0,"Size":0,"Specials":["special1","special2"],"Stuffed":0}
Result: {"NumberOfPizzas":2,"Size":0,"Kind":4,"Signature":0,"GourmetDelite":0,"Stuffed":0,"BYO":{"Crust":2,"Sauce":1,"HalfAndHalf":false,"Toppings":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24],"HalfToppings":null},"Coupons":[1,2],"Coupon":0,"DeliveryAddress":"2 Iowa St","Rating":2.5,"Available":"1962-02-25T15:00:00","Bottles":null,"Specials":["special1","special2"],"Phone":"123-4567"}
