en-us
{"Date":"0001-01-01T00:00:00","Float":null,"Integer":0,"SomeChoices":0,"Text":null}
[]
FromUser:"Hi"
1
ToUserText:"Please enter a number for float "
State:{"Date":"0001-01-01T00:00:00","Float":null,"Integer":0,"SomeChoices":0,"Text":null}
FromUser:"1.0"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":"","subtitle":null,"text":"Please select a some choices ","images":null,"buttons":[{"type":"imBack","title":"One","image":null,"text":null,"displayText":null,"value":"One"},{"type":"imBack","title":"Two","image":null,"text":null,"displayText":null,"value":"Two"},{"type":"imBack","title":"Three","image":null,"text":null,"displayText":null,"value":"Three"},{"type":"imBack","title":"Four","image":null,"text":null,"displayText":null,"value":"Four"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Date":"0001-01-01T00:00:00","Float":1.0,"Integer":0,"SomeChoices":0,"Text":null}
FromUser:"one"
1
ToUserText:"Please enter a number for float "
State:{"Date":"0001-01-01T00:00:00","Float":null,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"2.0"
1
ToUserText:"All OK?"
State:{"Date":"0001-01-01T00:00:00","Float":2.0,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"no"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":"","subtitle":null,"text":"What do you want to change? ","images":null,"buttons":[{"type":"imBack","title":"Float(2)","image":null,"text":null,"displayText":null,"value":"Float"},{"type":"imBack","title":"Some Choices(One)","image":null,"text":null,"displayText":null,"value":"Some Choices"},{"type":"imBack","title":"No Preference","image":null,"text":null,"displayText":null,"value":"No Preference"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Date":"0001-01-01T00:00:00","Float":2.0,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"Some Choices"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":"","subtitle":null,"text":"Please select a some choices ","images":null,"buttons":[{"type":"imBack","title":"One","image":null,"text":null,"displayText":null,"value":"One"},{"type":"imBack","title":"Two","image":null,"text":null,"displayText":null,"value":"Two"},{"type":"imBack","title":"Three","image":null,"text":null,"displayText":null,"value":"Three"},{"type":"imBack","title":"Four","image":null,"text":null,"displayText":null,"value":"Four"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Date":"0001-01-01T00:00:00","Float":2.0,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"one"
1
ToUserText:"Please enter a number for float "
State:{"Date":"0001-01-01T00:00:00","Float":null,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"3.0"
1
ToUserText:"All OK?"
State:{"Date":"0001-01-01T00:00:00","Float":3.0,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"no"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":"","subtitle":null,"text":"What do you want to change? ","images":null,"buttons":[{"type":"imBack","title":"Float(3)","image":null,"text":null,"displayText":null,"value":"Float"},{"type":"imBack","title":"Some Choices(One)","image":null,"text":null,"displayText":null,"value":"Some Choices"},{"type":"imBack","title":"No Preference","image":null,"text":null,"displayText":null,"value":"No Preference"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Date":"0001-01-01T00:00:00","Float":3.0,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"some choices"
1
ToUserButtons:[{"contentType":"application/vnd.microsoft.card.hero","contentUrl":null,"content":{"title":"","subtitle":null,"text":"Please select a some choices ","images":null,"buttons":[{"type":"imBack","title":"One","image":null,"text":null,"displayText":null,"value":"One"},{"type":"imBack","title":"Two","image":null,"text":null,"displayText":null,"value":"Two"},{"type":"imBack","title":"Three","image":null,"text":null,"displayText":null,"value":"Three"},{"type":"imBack","title":"Four","image":null,"text":null,"displayText":null,"value":"Four"}],"tap":null},"name":null,"thumbnailUrl":null}]
State:{"Date":"0001-01-01T00:00:00","Float":3.0,"Integer":0,"SomeChoices":1,"Text":null}
FromUser:"two"
1
ToUserText:"All OK?"
State:{"Date":"0001-01-01T00:00:00","Float":3.0,"Integer":0,"SomeChoices":2,"Text":null}
FromUser:"yes"
0
State:{"Date":"0001-01-01T00:00:00","Float":3.0,"Integer":0,"SomeChoices":2,"Text":null}
Result: {"Text":null,"Integer":0,"Float":3.0,"SomeChoices":2,"Date":"0001-01-01T00:00:00"}
